const textContainer = document.getElementsByClassName("text-container")[0],
  input = document.getElementById("hidden-input");
let start = !1;
const green = "green-text",
  red = "red-text",
  grey = "grey-text",
  yellow = "yellow-bg";
let totalKeys = 0,
  lang = 0,
  difficulty = 0;
const charString = [
  [
    [
      "the earth moves through its seasons with quiet certainty spring arrives with tender green shoots pushing through the cold soil and birds returning from distant lands to build their nests in familiar trees the air fills with pollen and the sound of running streams swollen with snowmelt summer brings long days of heat and light the tall grasses sway in warm breezes and bees move from flower to flower doing their ancient work butterflies drift through gardens and children play in rivers and lakes with joyful abandon autumn comes slowly at first just a hint of gold in the treetops before the full glory of red and orange and yellow spreads across the hillsides the harvest is gathered and stored against the cold to come then winter arrives and the world grows still and white frost forms on windowpanes and bare branches and animals sleep deep in their dens waiting for the warmth to return there is a kind of wisdom in this endless turning a reminder that nothing stays the same and that every ending is also a beginning the farmer knows this and plants seeds with faith that the sun and rain will do their work the gardener knows this and cuts back the old growth to make room for the new and the traveler walking through a forest in any season can feel this great cycle turning beneath their feet and in the wind around them and in the slow growth of the trees reaching upward toward the light year after year century after century the earth breathes and turns and blooms and rests and blooms again",
      "science has always begun with a question a small persistent wondering about why things are the way they are the first scientists were not people in laboratories but curious observers watching the sky and tracking the movements of stars they noticed patterns in the rising and setting of the sun and in the behavior of tides and animals and plants over generations these observations became knowledge and knowledge became the foundation of civilization the development of mathematics gave humans a precise language for describing the world and the invention of writing allowed discoveries to be recorded and shared across time and distance the scientific method as it came to be known is built on the idea that ideas must be tested against reality and that no authority can override what careful observation reveals this has led to an extraordinary accumulation of understanding about the universe from the laws of motion to the structure of atoms to the mechanisms of heredity and the nature of light each discovery has opened new questions and each answer has revealed new mysteries the universe it turns out is far stranger and more wonderful than any early thinker could have imagined and yet the basic impulse that drives science is as old as humanity itself the desire to understand to know to see through appearances to the underlying order of things this desire has built the modern world and it continues to push at the boundaries of what is known driving us further into the unknown with every generation",
      "the history of human civilization is a story of people coming together to solve shared problems the earliest communities formed around sources of water and food and the need to protect one another from danger over thousands of years these small groups grew into villages towns and eventually great cities with complex systems of government law trade and culture the rise of agriculture allowed populations to grow far beyond what hunting and gathering could support and with larger populations came specialization some people farmed while others built wove traded taught healed and governed the great civilizations of the ancient world built remarkable things pyramids temples aqueducts and libraries that still astonish us today they developed writing systems that allowed knowledge to be preserved and passed on laws that governed behavior and art that expressed the deepest human feelings the fall of empires and the rise of new ones the movements of peoples across continents the struggles for freedom and justice and equality all of this is the long complicated story of how we came to be who we are today understanding history is not merely about memorizing dates and names it is about understanding the forces that shape human life and the choices that individuals and societies make when faced with difficulty and the enduring human qualities of courage creativity and the desire to build something lasting",
      "the ocean covers more than two thirds of the surface of the earth and yet it remains one of the least explored regions of the planet its depths hold creatures and landscapes that most humans will never see mountains taller than any on land trenches deeper than the highest peaks forests of coral teeming with life and vast dark plains where strange luminous creatures drift through eternal cold water the ocean regulates the temperature of the earth and drives the weather patterns that bring rain to the continents it absorbs enormous quantities of heat and carbon dioxide from the atmosphere and generates more than half of the oxygen we breathe the currents that move through the ocean act like a great circulatory system distributing warmth and nutrients around the globe the creatures of the sea have evolved over hundreds of millions of years developing extraordinary adaptations to their environments from the smallest plankton to the largest whale every species plays a role in maintaining the health of the ocean ecosystem the relationship between humans and the ocean is ancient and deep coastal peoples have always depended on it for food and trade and the salt air and sound of waves have inspired art music and literature across every culture the health of the ocean is the health of the planet and understanding and protecting it is one of the great responsibilities of our time",
      "the human brain is the most complex structure known to exist in the universe containing roughly eighty six billion neurons each connected to thousands of others through a web of synapses that number in the hundreds of trillions the electrical and chemical signals that pass through this network give rise to everything we experience as human life thought memory emotion imagination language love and the awareness of our own existence neuroscience has made enormous progress in understanding how different regions of the brain contribute to different functions and how damage to those regions affects behavior and personality brain imaging technologies have allowed scientists to watch the living brain at work and to see which areas become active when a person solves a problem hears music or feels fear yet the deepest questions about the brain remain unanswered how does the physical activity of neurons give rise to the subjective experience of being conscious why does the brain create a sense of a unified self from so many separate processes how is it that memories can last a lifetime stored in patterns of connection that are constantly changing these questions sit at the boundary between neuroscience and philosophy and answering them will require new kinds of thinking and new tools the study of the brain is in many ways the study of what it means to be human",
      "cities have always been places where human energy concentrates and new things become possible when people from different backgrounds and disciplines live and work close together ideas collide and recombine in unexpected ways the great cities of history athens alexandria baghdad florence london paris new york have all been centers of innovation not only in technology and commerce but in art philosophy literature and political thought the urban environment with its density and diversity creates a particular kind of stimulation that seems to accelerate human creativity the coffee houses of london where merchants and philosophers argued over newspapers the salons of paris where writers and artists gathered to read their work to one another the university towns where young people from across a country came to study together all of these were engines of cultural change cities also concentrate problems poverty crime disease inequality and the struggle to make a life in a competitive and crowded environment has always tested the character of both individuals and institutions the history of urban planning is a history of attempts to solve these problems with mixed results the cities of the future will need to be more sustainable more equitable and more resilient than those of the past meeting these challenges while preserving what makes cities vital and exciting will require creativity wisdom and a deep commitment to the wellbeing of all their inhabitants",
      "the art of cooking is one of the oldest and most universal human practices fire transformed raw food into something that not only tasted better but was easier to digest and safer to eat and this discovery may have played a crucial role in the evolution of the human brain by making more calories available from the same amount of food over thousands of years every culture on earth developed its own cuisine shaped by the ingredients available in its environment the spices of india the noodles of china the olive oil and herbs of the mediterranean the corn and chili of the americas all of these culinary traditions represent accumulated wisdom about flavor nutrition and the pleasures of eating food is never just fuel it is culture memory identity and care when we share a meal with others we are participating in one of the most ancient forms of human connection the recipes passed down through families carry within them the voices of grandmothers and great grandmothers who cooked in very different kitchens with very different tools but with the same desire to nourish and delight the people they loved cooking well requires patience practice and a willingness to learn from failure it demands attention to detail and sensitivity to ingredients that vary with the season and the soil and it rewards those who approach it with curiosity and respect",
      "sport at its best is more than competition it is a form of human expression as rich and varied as music or painting the athlete in full motion achieves something that is both beautiful and meaningful the sprinter accelerating off the blocks the gymnast turning in the air the soccer player controlling a ball with effortless precision these are acts of mastery that audiences recognize and respond to with something deeper than mere appreciation for skill sport also teaches things that are hard to learn any other way how to lose with dignity how to win without arrogance how to work with others toward a shared goal how to persevere when the body is exhausted and the mind wants to give up the bond between teammates who have trained and competed together is one of the strongest kinds of human connection forged in shared effort and shared vulnerability sport has the power to cross barriers of language culture and nationality bringing people together around a common passion the great moments of sporting history a relay race won by a fraction of a second a comeback from an apparently hopeless deficit a performance so extraordinary it seems to transcend what the human body should be capable of these moments become part of the shared memory of those who witnessed them passing from person to person as stories that carry something essential about what human beings can do when they are fully alive and fully committed",
      "philosophy asks the questions that other disciplines take for granted what is knowledge what is reality what makes an action right or wrong what is the good life these are not questions with easy answers but the act of asking them carefully and honestly has shaped human thought in profound ways the ancient greek philosophers sat in public places and engaged anyone willing to think alongside them they believed that an unexamined life was not worth living and that reason was the highest human capacity their ideas about democracy justice the soul and the nature of reality influenced every civilization that came after them in the eastern world thinkers in india and china were developing equally sophisticated ways of understanding human experience and the cosmos confucius taught that social harmony depended on the cultivation of virtue the buddha taught that suffering arose from desire and could be overcome through right understanding and right action the great hindu texts explored the relationship between the individual self and the universal consciousness these traditions though very different in their methods and conclusions share a common faith in the power of human thought to illuminate the deepest questions of existence today philosophy continues to grapple with questions about consciousness free will the nature of meaning the ethics of technology and what it means to live well in a complex and uncertain world",
      "the universe began approximately thirteen point eight billion years ago in an event that released all the matter and energy that would ever exist in a form so dense and hot that the laws of physics as we currently understand them break down in the first fraction of a second after this beginning the universe expanded faster than the speed of light cooling as it grew and allowing the first subatomic particles to form from these particles came hydrogen and helium the simplest elements and from great clouds of hydrogen and helium the first stars ignited burning for millions of years before dying in tremendous explosions that scattered heavier elements across space from these elements new stars formed with planets orbiting them and on at least one of those planets in an unremarkable corner of an ordinary galaxy the right conditions came together for life to emerge the story of the universe is the story of increasing complexity from simple particles to atoms to molecules to stars to planets to living things and eventually to minds capable of contemplating the whole vast process we are made of atoms forged in the hearts of ancient stars and the light we see in the night sky left those distant suns thousands or millions of years ago we are in the most literal sense children of the cosmos",
    ],
    [
      "The seasons turn with a quiet, inevitable certainty. Spring arrives first, pushing tender green shoots through cold soil; birds return from warmer lands, and the air fills with their songs. \"It's the best time of year,\" farmers say, stepping into their fields on cool mornings. Summer follows — long, golden, full of heat and light. Children swim in rivers, and bees move from flower to flower with patient industry. Then autumn comes; the hillsides flame with red and gold, and the harvest is gathered before winter's first frost. Winter, too, has its beauty: the still, white world; the long nights; the fires burning in hearths. Each season is a chapter in a story that has been telling itself since long before there were humans to notice it. To live close to the land is to understand this rhythm in your bones — to know that every ending is a beginning, and that patience is not passive waiting but active faith.",
      'Science, at its heart, is a method: observe, hypothesize, test, revise. It sounds simple, but the discipline it requires is extraordinary. "The first principle," Feynman said, "is that you must not fool yourself — and you are the easiest person to fool." Every great scientific discovery has demanded that someone be willing to say: "What I believed is wrong." Copernicus placed the sun at the center of the solar system; Darwin showed that species change over time; Einstein revealed that space and time are not fixed. Each of these ideas overturned centuries of assumption, and each was resisted before it was accepted. Science is not a collection of facts; it is a living process — always questioning, always revising, always moving toward greater accuracy. Its power comes not from certainty, but from its structured willingness to be uncertain. In an age when false confidence is everywhere, this is perhaps science\'s most important lesson.',
      'History is never simply the past; it is a conversation that the present holds with what came before. We read the records of ancient civilizations — their laws, their letters, their art — and we find in them something startlingly familiar: the same ambitions, the same fears, the same impulse to build something that will outlast a single life. "The more things change," the saying goes, "the more they stay the same." And yet things do change; sometimes slowly, sometimes with shocking speed. The abolition of slavery, the extension of voting rights, the end of colonial empires — these were not inevitable; they were won through struggle. Understanding history means understanding both continuity and change, and resisting the temptation to see the past as simply a cruder version of the present. People in earlier times were not less intelligent than we are; they were differently situated, with different information, different pressures, and different possibilities.',
      'Philosophy begins, as Aristotle said, in wonder. Why does anything exist at all? What can we know, and how can we know it? What do we owe to one another? These questions resist easy answers — and that is precisely their value. To sit with a hard question, to turn it over carefully, to consider it from multiple angles without rushing to a conclusion: this is a discipline that has practical consequences. The person who has thought seriously about ethics is better prepared to act well under pressure. The person who has examined their own assumptions is less likely to be deceived by slogans or by their own wishful thinking. "Know thyself," the inscription at Delphi urged — and Socrates spent his life pursuing that instruction, irritating nearly everyone he met in the process. Philosophy does not promise comfortable answers. It promises something more valuable: the ability to ask better questions, and to live with greater clarity and purpose.',
      'The human brain, with its billions of neurons and trillions of connections, is the most complex object we have yet discovered in the universe. It creates the world we experience — not just perceiving reality, but actively constructing it from sensory signals, memories, and expectations. "We don\'t see things as they are," Anaïs Nin wrote, "we see them as we are." Neuroscience has confirmed something like this: the brain is not a passive receiver but a relentless interpreter, filling in gaps, making predictions, and shaping experience to match what it already believes. This is useful — it is what allows us to act quickly in a complex world — but it also means we are all, to some degree, living in a story our brains are telling us. Understanding this is not cause for despair; it is an invitation to be more thoughtful, more curious, and more humble about our perceptions. The study of the brain is, in the deepest sense, the study of what it means to be human.',
      'The ocean is a world unto itself. Its surface, seen from shore, gives little hint of what lies beneath: mountain ranges, plains, canyons deeper than anything on land, and creatures of extraordinary strangeness and beauty. The anglerfish dangles its luminous lure in the pitch-dark deep; the blue whale — the largest animal ever known — moves through cold water with unhurried grace; the coral reef, teeming with color, supports a density of life that rivals the tropical rainforest. "The sea is everything," Jules Verne wrote. "It covers seven-tenths of the terrestrial globe." And yet we know more about the surface of the moon than about the deepest ocean trenches. This is changing; new submersibles, new sensors, and new methods of analysis are revealing the deep ocean\'s secrets. What scientists find there may transform our understanding of life itself — including the possibility that life began, not in some warm coastal pool, but in the crushing dark of the ocean floor.',
      'Cities are where the future gets made. The density of people, ideas, and institutions in a great city creates a kind of creative friction — accidental conversations, unexpected collaborations, the collision of knowledge from different fields. "The city," Jane Jacobs argued, "is not a problem to be solved; it is a complex, living ecosystem that must be understood and supported." The great cities of history have always been diverse: merchants and scholars, artists and officials, migrants from distant provinces and visitors from foreign lands, all pressing together in narrow streets or broad boulevards. Out of this pressure came the Florentine Renaissance, the Enlightenment, the Harlem Renaissance, Silicon Valley. Cities also concentrate problems; poverty, inequality, and the stress of dense living are as much a part of urban history as the cathedrals and universities. The challenge of the coming century will be to build cities that are productive and vibrant without being unjust and unsustainable — places where the benefits of urban life are shared more broadly than they have been in the past.',
      'Cooking is a form of care made tangible. To prepare a meal for someone is to say, without words: "I see you; I want you to be nourished; I have given my time and attention to your pleasure." The greatest cuisines of the world grew from this impulse, refined over centuries by cooks who paid close attention to what tasted good and why. Salt, fat, acid, and heat are the fundamental tools; everything else is elaboration. A simple dish — a bowl of broth, a piece of bread, a plate of beans cooked with herbs — can be as satisfying as an elaborate banquet if it is made with good ingredients and genuine care. "Cooking is one of the strongest ceremonies for life," the chef Clarissa Dickson Wright said. There is something almost miraculous in the transformation of raw ingredients into a meal: the way heat changes texture and flavor, the way spices from distant continents find their way into a family kitchen and become part of that family\'s story. To cook is to participate in a very long, very human tradition.',
      'The universe, as far as we can tell, is about 13.8 billion years old. For most of that time, there were no planets, no life, and no minds to contemplate the whole extraordinary process. Stars formed and burned and exploded, seeding space with heavy elements. Galaxies collided and merged. Slowly — on a cosmic timescale — the conditions for life came together in certain places. On Earth, something remarkable happened: matter organized itself into living things, and living things eventually organized themselves into beings capable of asking where they came from. "We are a way for the cosmos to know itself," Carl Sagan said. This idea — that human consciousness is the universe\'s way of reflecting on its own existence — is both humbling and exhilarating. We are small: our planet is a pale blue dot in an ordinary galaxy among hundreds of billions of galaxies. But we are also extraordinary: as far as we know, nothing else in all that vast darkness wonders at its own existence the way we do.',
      "Sport distills something essential about being human: the desire to test limits, to compete with grace, and to push the body and mind toward their furthest edges. At the highest levels, great athletes achieve something that looks almost effortless — but that apparent ease is built on thousands of hours of unglamorous work. Muhammad Ali shadowboxing at dawn; Serena Williams drilling forehands until her arm ached; Michael Jordan, famously, practicing the shots he had missed in games so he would not miss them again. \"I've missed more than 9,000 shots in my career,\" Jordan said. \"I've lost almost 300 games. Twenty-six times, I've been trusted to take the game-winning shot and missed. I've failed over and over again in my life. And that is why I succeed.\" This is the paradox at the heart of sport, and of much human achievement: failure, embraced honestly and learned from, is not the opposite of success. It is its foundation.",
    ],
    [
      'The startup ecosystem runs on a simple formula: find a problem, build a solution, and scale it fast. But the reality is far messier. "You want to change the world?" a mentor once told a founder. "First, make sure your servers don\'t crash at 2 a.m." The technical stack matters — Python, React, Node.js, PostgreSQL — but culture matters more. A team that communicates well (and argues productively) will out-build a team with a superior tech stack every time. Revenue models vary: some companies charge $9.99/month per user; others take a 2% fee on every transaction; still others sell enterprise licenses at $50,000+/year. The key metric — whether it\'s DAU, MRR, or NPS — depends on the business. What doesn\'t change is the need for honesty: with investors, with users, and (most importantly) with yourself. The best founders ask hard questions: Why would someone pay $20 for this instead of the free alternative? What happens when a competitor undercuts us by 30%? Is this a vitamin or a painkiller?',
      'Programming is, at its core, a discipline of clear thinking. The code you write is a precise instruction to a machine — it does exactly what you tell it, no more and no less. This is both liberating and humbling. A missing semicolon, a misplaced bracket, an off-by-one error in a loop (starting at i=1 when it should start at i=0) can cause a program to behave in ways that are baffling until they are obvious. The best developers write code that humans can read as easily as machines can run: clear variable names, small functions that do one thing well, and comments that explain *why* rather than just what. "Any fool can write code a computer can understand," Martin Fowler noted. "Good programmers write code that humans can understand." Version control (git), testing (unit & integration), and documentation are not optional extras — they are the difference between a project that thrives and one that collapses under its own weight. The semicolon costs nothing. The habit of clarity costs everything; it\'s worth it.',
      "Data science sits at the intersection of statistics, programming, and domain knowledge. A data scientist might spend a morning writing SQL queries — SELECT user_id, COUNT(*) FROM events WHERE event_type = 'purchase' GROUP BY user_id — and an afternoon building a machine learning model to predict which users are likely to churn. The tools change fast: yesterday it was R; today it's Python (pandas, scikit-learn, PyTorch); tomorrow it might be something nobody has built yet. But the underlying questions don't change. What does this data actually tell us? Where is it incomplete or biased? Is this correlation or causation? A 15% lift in click-through rate sounds impressive — but if the sample size is 80 users, it means almost nothing. Statistical significance (p < 0.05) is a starting point, not an ending point. \"In God we trust,\" W. Edwards Deming said; \"all others bring data.\" The caveat he might add today: bring *good* data, collected with care, interpreted with humility, and communicated with honesty. Numbers don't lie, but they can be made to mislead.",
      'The modern web is built on a stack of technologies that interact in intricate ways. At the base is HTTP/HTTPS — the protocol that governs how browsers request resources and servers respond. A typical request might look like: GET /api/users/42 HTTP/1.1, and a response: {"id": 42, "name": "Priya", "role": "admin"}. On top of HTTP sits the application layer: REST APIs, GraphQL endpoints, WebSockets for real-time communication. The frontend (HTML + CSS + JavaScript) renders what users see; the backend (Node, Django, Rails, Go) handles logic and data. Databases sit below: relational (PostgreSQL, MySQL), document (MongoDB), key-value (Redis), or graph (Neo4j). Security threads through all of it: HTTPS encrypts transit; bcrypt hashes passwords; JWTs authenticate sessions; rate limiting (100 req/min per IP) prevents abuse. It sounds complicated — and it is — but each layer solves a specific problem, and understanding the whole stack makes you a far more effective developer than knowing only one piece. "The web is not a single technology," someone once said. "It\'s a conversation between thousands of technologies, happening billions of times per second."',
      "Finance is the language of trade, and learning it is not optional for anyone who wants to understand the modern world. A balance sheet has two sides: assets (what you own — cash, inventory, equipment) and liabilities + equity (what you owe and what's left over). The equation is always: Assets = Liabilities + Equity. An income statement shows revenue - expenses = profit (or loss). Cash flow is different from profit: a company can be profitable on paper and still run out of cash if customers pay slowly (Net-60 terms) while suppliers demand payment upfront. Valuation is an art as much as a science: a startup might be valued at 10× revenue, while a mature company trades at 15-20× earnings. Interest rates matter enormously — when the Fed raises rates by 0.25%, the effect ripples through mortgages, bond prices, stock valuations, and currency exchange rates. Understanding these connections doesn't require a degree in economics; it requires attention, a few good books, and the habit of asking: \"Who benefits? Who bears the risk? What happens if this assumption turns out to be wrong?\" These questions have no perfect answers — but asking them is what separates clear thinking from wishful thinking.",
      'Cybersecurity is the discipline of protecting systems, networks, and data from attacks. The threat landscape includes: phishing (fake emails that steal credentials), SQL injection (malicious input like \' OR 1=1; -- that tricks a database), cross-site scripting (XSS), ransomware (encrypting data and demanding $50,000 in BTC to restore it), and supply chain attacks (compromising a library that thousands of applications use). Defense starts with basics: strong, unique passwords (use a manager — 1Password, Bitwarden); two-factor authentication (2FA); software updates applied promptly; least-privilege access (give users only the permissions they actually need). For developers, the OWASP Top 10 is essential reading — it catalogs the most common security vulnerabilities in web applications. Encryption matters: data should be encrypted at rest (AES-256) and in transit (TLS 1.3). "Security is not a product," Bruce Schneier said; "it is a process." No system is 100% secure, but the goal is to make attacking you more expensive than the reward — raising the cost until most adversaries give up and look for an easier target.',
      "The gig economy — platforms like Uber, Airbnb, Fiverr, and Upwork — has reshaped how work is organized. For workers, the appeal is flexibility: set your own hours, choose your own clients, work from anywhere. For companies, the appeal is efficiency: pay only for what you need, scale up or down instantly, avoid the overhead of full-time employment. But the costs are real: no health insurance, no paid leave, no unemployment benefits, no path to a pension. A driver earning $25/hr gross might net $12/hr after expenses (gas: ~$8/hr; depreciation: ~$3/hr; insurance: ~$2/hr) — and that's before taxes (self-employment tax is 15.3% on top of income tax). The debate about whether gig workers should be classified as employees (entitled to benefits) or independent contractors (responsible for their own costs) is playing out in courts and legislatures around the world. California's AB5, the UK Supreme Court's Uber ruling, and the EU's proposed platform work directive represent very different answers to the same question: \"In a world where 30-40% of workers are contingent, who is responsible for their security?\"",
      "E-commerce has transformed retail in ways that are still unfolding. The numbers are staggering: global e-commerce sales exceeded $5 trillion in 2022, growing at ~10-15%/year. Amazon, Alibaba, Shopify, and a thousand smaller platforms have made it possible for a single person to sell products to customers on the other side of the world without ever touching a warehouse. The economics of online retail are different from physical retail: customer acquisition cost (CAC) often runs $20-$80 per customer; return rates for online fashion can reach 40%; logistics (last-mile delivery) represents 30-50% of total shipping cost. Search engine optimization (SEO), pay-per-click advertising (PPC at $0.50-$5.00 per click), email marketing (ROI: ~$42 per $1 spent), and influencer partnerships all compete for budget. Behind the scenes, inventory management is critical: too much stock ties up cash; too little means lost sales (stockout rate > 5% damages customer trust significantly). The companies that win in e-commerce are not necessarily those with the best products — they are the ones that understand their unit economics deeply and optimize every step of the funnel from first click to repeat purchase.",
      'Artificial intelligence is not magic; it is applied mathematics, statistics, and large amounts of carefully curated data. A neural network — the architecture behind most modern AI systems — is a function with billions of parameters (weights) that transform an input (an image, a sentence, a board position) into an output (a classification, a translation, a move). Training adjusts these weights by gradient descent: compute the error on a batch of examples, calculate the gradient (∂Loss/∂W), and nudge the weights in the direction that reduces loss. Repeat for millions of batches. The result is a model that has, in some sense, "learned" from the data — but what it has learned is statistical patterns, not the deep understanding that humans bring to problems. This is why large language models can write fluent prose and still confidently state false facts: they are optimizing for plausible sequences of tokens, not for truth. The capabilities are remarkable (GPT-4, Claude, Gemini); so are the risks (bias in training data @ scale, misuse, displacement of jobs). "AI is a tool," one researcher put it. "Like all tools, what matters is who uses it, how, and to what end — with what safeguards (✓), with what honesty about limitations (✓), and with what concern for those affected (#priorities)."',
      'The global supply chain is a marvel of coordination — and a source of extraordinary fragility. A modern smartphone contains components manufactured in dozens of countries: lithium from Chile ($6,000/tonne), rare earth elements from China, silicon wafers from Japan, OLED screens from South Korea, and assembled (for ~$10/unit in labor) in factories in China, Vietnam, and India before being shipped to consumers worldwide. This works beautifully when everything goes smoothly. When it doesn\'t — a pandemic shuts down factories, a ship blocks the Suez Canal for 6 days, a fire destroys a single semiconductor fab — the cascading effects can idle car plants, empty store shelves, and cost the global economy hundreds of billions of dollars. "Just in time" manufacturing (keeping inventory at near-zero levels) maximizes efficiency but minimizes resilience. The pandemic of 2020-2022 revealed the true cost of that trade-off. Companies and governments are now rethinking: How much should we pay (in $ and in efficiency) for supply chain resilience? Where is strategic self-sufficiency worth its cost? These are not purely technical questions — they are questions about values, risk tolerance, and the kind of world we want to build.',
    ],
  ],
  [
    [
      "सूरज हर सुबह उगता है और अपनी सुनहरी किरणों से धरती को रोशन करता है खेतों में किसान अपना काम शुरू करते हैं और हवा में फूलों की खुशबू फैल जाती है नदी किनारे बच्चे खेलते हैं और पक्षी पेड़ों पर गाने गाते हैं पहाड़ों पर बर्फ चमकती है और घाटियों में हरियाली होती है भारत की धरती पर अनेक प्रकार के मौसम आते हैं बसंत में फूल खिलते हैं और पेड़ों पर नई पत्तियां आती हैं गर्मियों में धूप तेज होती है और लोग ठंडी छाया में बैठते हैं बरसात में बादल घिरते हैं और बारिश की बूंदें धरती को भिगोती हैं सर्दियों में कोहरा छाता है और ठंडी हवाएं चलती हैं प्रकृति का यह चक्र सदियों से चला आ रहा है और इसमें एक गहरी सुंदरता है जो मन को शांत करती है जब हम प्रकृति के करीब होते हैं तो हमें जीवन की सच्चाई का एहसास होता है और हमारा मन शांत होता है",
      "विज्ञान ने मनुष्य के जीवन को बदल दिया है पहले लोग अंधेरे में मोमबत्तियों की रोशनी में काम करते थे आज बिजली हर घर में रोशनी भर देती है पहले यात्राएं महीनों में होती थीं अब हवाई जहाज घंटों में दुनिया के किसी भी कोने में पहुंचा देते हैं दवाइयों की खोज ने लाखों लोगों की जानें बचाई हैं और टीकों ने खतरनाक बीमारियों को जड़ से खत्म कर दिया है कंप्यूटर और इंटरनेट ने ज्ञान को सबके लिए सुलभ बना दिया है कोई भी अपने घर से दुनिया के किसी भी विश्वविद्यालय की पुस्तकें पढ़ सकता है वैज्ञानिक हर दिन नई खोजें कर रहे हैं जो हमारे भविष्य को और बेहतर बनाएंगी अंतरिक्ष में भेजे गए यान दूसरे ग्रहों की जानकारी लेकर आते हैं और हमें यह बताते हैं कि ब्रह्मांड कितना विशाल और रहस्यमय है विज्ञान की इस यात्रा में जिज्ञासा और खोज की भावना ही सबसे बड़ी शक्ति है",
      "भारत का इतिहास हजारों वर्षों पुराना है यहां की सभ्यता दुनिया की सबसे प्राचीन सभ्यताओं में से एक है सिंधु घाटी की सभ्यता से लेकर मौर्य साम्राज्य गुप्त वंश मुगल काल और ब्रिटिश शासन तक भारत ने बहुत कुछ देखा है इस देश ने दुनिया को शून्य का ज्ञान दिया गणित में क्रांति लाई और दर्शन साहित्य और कला में अमूल्य योगदान दिया महात्मा गांधी ने अहिंसा के रास्ते से आजादी दिलाई और पूरी दुनिया को यह सिखाया कि शांति से भी बड़े से बड़े बदलाव लाए जा सकते हैं भारत की विविधता इसकी सबसे बड़ी ताकत है यहां अनेक भाषाएं बोली जाती हैं अनेक धर्मों के लोग साथ मिलकर रहते हैं और अनेक परंपराएं एक साथ जीवित हैं यह विविधता में एकता का अद्भुत उदाहरण है जो पूरी दुनिया के लिए प्रेरणा का स्रोत है भारतीय संस्कृति में परिवार और समाज को बहुत महत्व दिया जाता है",
      "शिक्षा वह दीपक है जो अज्ञान के अंधेरे को मिटाता है एक शिक्षित व्यक्ति न केवल अपने लिए बल्कि अपने समाज और देश के लिए भी उपयोगी होता है जब एक बच्चा पहली बार स्कूल जाता है तो वह एक नई दुनिया में प्रवेश करता है जहां उसे न केवल पढ़ना और लिखना सिखाया जाता है बल्कि उसे जीवन जीने का तरीका भी सिखाया जाता है अच्छे शिक्षक छात्रों के जीवन में बड़ा बदलाव लाते हैं वे न केवल ज्ञान देते हैं बल्कि प्रेरणा देते हैं और सोचने की क्षमता विकसित करते हैं पुस्तकें मानव जाति का सबसे बड़ा खजाना हैं इनमें सदियों का ज्ञान और अनुभव संचित है जो कोई पुस्तकें पढ़ता है वह अपने समय से आगे चलता है और जीवन की चुनौतियों का सामना बेहतर तरीके से कर पाता है आज के युग में डिजिटल शिक्षा ने ज्ञान को और भी सुलभ बना दिया है और दूर दराज के गांवों में बैठे बच्चे भी अच्छी शिक्षा पा सकते हैं",
      "खेल मनुष्य के जीवन का एक महत्वपूर्ण हिस्सा है क्रिकेट भारत का सबसे लोकप्रिय खेल है जो करोड़ों लोगों को एक सूत्र में बांधता है जब भारतीय क्रिकेट टीम मैदान पर उतरती है तो पूरा देश एक हो जाता है फुटबॉल हॉकी बैडमिंटन कुश्ती और कबड्डी जैसे खेल भी भारत में बहुत लोकप्रिय हैं खेलों से न केवल शरीर स्वस्थ रहता है बल्कि मन भी मजबूत होता है खिलाड़ी टीम भावना अनुशासन और हार जीत को स्वीकार करने का हुनर सीखते हैं ये गुण जीवन के हर क्षेत्र में काम आते हैं महान खिलाड़ी सचिन तेंदुलकर मिल्खा सिंह पीटी उषा और नीरज चोपड़ा ने अपनी कड़ी मेहनत और लगन से न केवल भारत का नाम रोशन किया बल्कि लाखों युवाओं को प्रेरणा भी दी ग्रामीण क्षेत्रों में भी खेल प्रतिभाएं हैं जिन्हें सही मार्गदर्शन और सुविधाएं मिलें तो वे विश्व स्तर पर अपना नाम कमा सकती हैं",
      "भारतीय खाना अपनी विविधता और स्वाद के लिए पूरी दुनिया में मशहूर है उत्तर से दक्षिण और पूर्व से पश्चिम तक हर क्षेत्र की अपनी खास व्यंजन परंपरा है पंजाब की दाल मखनी और बटर चिकन दक्षिण भारत के इडली डोसा और सांभर महाराष्ट्र की पूरन पोली और मिसल पाव राजस्थान की दाल बाटी चूरमा और गुजरात का ढोकला खाखरा ये सभी अपने आप में एक पूरी संस्कृति को समेटे हुए हैं भारतीय मसाले जैसे हल्दी जीरा धनिया इलायची और दालचीनी न केवल खाने को स्वादिष्ट बनाते हैं बल्कि सेहत के लिए भी बेहद फायदेमंद होते हैं भोजन तैयार करना भारत में एक कला है जो पीढ़ी दर पीढ़ी चलती आई है माँ के हाथ का खाना सिर्फ पेट ही नहीं भरता बल्कि मन को भी तृप्त करता है त्योहारों पर बनने वाले विशेष पकवान उस उत्सव की याद को और भी गहरा बना देते हैं",
      "नदियां भारत की सभ्यता की जीवनरेखा हैं गंगा यमुना सरस्वती नर्मदा कावेरी और ब्रह्मपुत्र जैसी नदियों के किनारे ही भारतीय सभ्यता का विकास हुआ है इन नदियों का पानी लाखों किसानों के खेतों की प्यास बुझाता है और करोड़ों लोगों को पीने का पानी देता है गंगा को माँ का दर्जा दिया गया है और इसके किनारे बसे वाराणसी हरिद्वार और प्रयागराज जैसे शहर धार्मिक और सांस्कृतिक दृष्टि से अत्यंत महत्वपूर्ण हैं लेकिन आज ये नदियां प्रदूषण के खतरे से जूझ रही हैं कारखानों का कचरा और शहरों का गंदा पानी इन्हें दूषित कर रहा है इन्हें बचाना हमारी जिम्मेदारी है नदी संरक्षण के लिए जन जागरूकता जरूरी है हर व्यक्ति को यह समझना होगा कि नदियों की स्वच्छता से ही हमारा भविष्य सुरक्षित है",
      "भारत का ग्रामीण जीवन एक अलग ही दुनिया है जहां जीवन की गति शांत और सरल है सुबह होते ही खेतों में काम शुरू होता है किसान अपनी भैंस गाय लेकर खेत जाते हैं और महिलाएं घर का काम करने के साथ साथ खेती में भी हाथ बटाती हैं गांव की चौपाल पर बुजुर्ग बैठकर बातें करते हैं और बच्चे खेल मैदान में दौड़ते भागते हैं शाम को मंदिर में आरती होती है और लोग एक साथ मिलकर प्रार्थना करते हैं त्योहारों पर पूरा गांव एक परिवार की तरह जुड़ जाता है होली दीवाली ईद और क्रिसमस सभी त्योहार मिलजुल कर मनाए जाते हैं हालांकि आज गांव भी बदल रहे हैं सड़कें बन रही हैं बिजली पहुंच रही है और मोबाइल फोन ने दूरियां कम कर दी हैं लेकिन गांव की वह सादगी और अपनापन अभी भी बनी हुई है जो शहरों में मुश्किल से मिलती है",
      "पर्यावरण की रक्षा आज के समय की सबसे बड़ी जरूरत है जलवायु परिवर्तन पूरी दुनिया के सामने एक बड़ी चुनौती बन गया है बढ़ता तापमान पिघलते ग्लेशियर बेमौसम बारिश और बाढ़ सूखा ये सब इसके संकेत हैं पेड़ों की अंधाधुंध कटाई कारखानों से निकलने वाला धुआं और वाहनों का प्रदूषण वायु को दूषित कर रहा है प्लास्टिक का अत्यधिक उपयोग समुद्रों और नदियों को प्रदूषित कर रहा है इन समस्याओं से निपटने के लिए व्यक्तिगत और सामूहिक दोनों स्तरों पर प्रयास जरूरी हैं पेड़ लगाना सौर ऊर्जा का उपयोग करना प्लास्टिक से बचना और पानी बचाना ये छोटे छोटे कदम मिलकर बड़ा बदलाव ला सकते हैं भविष्य की पीढ़ियों के लिए एक स्वस्थ और सुंदर धरती छोड़ना हमारी जिम्मेदारी है और इस जिम्मेदारी को हमें आज से ही निभाना शुरू करना होगा",
      "संगीत मनुष्य की आत्मा की भाषा है भारतीय शास्त्रीय संगीत की परंपरा हजारों वर्षों पुरानी है रागों में सात सुर होते हैं सा रे ग म प ध नि और इन्हीं सुरों से लाखों राग रागिनियां बनती हैं भोर में भैरवी बजती है तो शाम को राग यमन सुनाई देता है हिंदुस्तानी और कर्नाटक दोनों संगीत परंपराओं ने भारतीय संस्कृति को समृद्ध किया है लता मंगेशकर रफी किशोर और आशा भोसले ने अपनी आवाज से करोड़ों दिलों को छुआ है लोक संगीत भी उतना ही महत्वपूर्ण है राजस्थानी मांड पंजाबी भांगड़ा बंगाली बाउल और तमिल लोकगीत अपने अपने क्षेत्र की संस्कृति की झलक देते हैं आज की युवा पीढ़ी पश्चिमी संगीत के साथ साथ भारतीय शास्त्रीय संगीत को भी अपना रही है और इस मिश्रण से नई और अद्भुत संगीत शैलियां जन्म ले रही हैं",
    ],
    [
      'सूरज हर सुबह उगता है, और अपनी सुनहरी किरणों से धरती को रोशन करता है। खेतों में किसान अपना काम शुरू करते हैं, और हवा में फूलों की खुशबू फैल जाती है। नदी किनारे बच्चे खेलते हैं, पक्षी पेड़ों पर गाने गाते हैं। प्रकृति का यह संगीत कितना मनोहर है! बसंत में फूल खिलते हैं, पेड़ों पर नई पत्तियां आती हैं। गर्मियों में धूप तेज होती है; लोग ठंडी छाया में बैठते हैं। बरसात में बादल घिरते हैं, और बारिश की बूंदें धरती को भिगोती हैं। सर्दियों में कोहरा छाता है, ठंडी हवाएं चलती हैं। "प्रकृति से बड़ा शिक्षक कोई नहीं," बुजुर्ग कहते हैं। यह चक्र सदियों से चला आ रहा है, और इसमें एक गहरी सुंदरता है — जो मन को शांत करती है।',
      'विज्ञान ने मनुष्य के जीवन को बदल दिया है। पहले लोग अंधेरे में मोमबत्तियों की रोशनी में काम करते थे; आज बिजली हर घर में रोशनी भर देती है। "यह युग विज्ञान का युग है," वैज्ञानिक कहते हैं। दवाइयों की खोज ने लाखों लोगों की जानें बचाई हैं, और टीकों ने खतरनाक बीमारियों को जड़ से खत्म कर दिया है। कंप्यूटर और इंटरनेट ने ज्ञान को सबके लिए सुलभ बना दिया है — कोई भी अपने घर से दुनिया के किसी भी विश्वविद्यालय की पुस्तकें पढ़ सकता है। वैज्ञानिक हर दिन नई खोजें कर रहे हैं। क्या हम जानते हैं कि अंतरिक्ष में कितने तारे हैं? विज्ञान की इस यात्रा में जिज्ञासा, धैर्य, और खोज की भावना ही सबसे बड़ी शक्ति है।',
      'भारत का इतिहास हजारों वर्षों पुराना है। यहां की सभ्यता दुनिया की सबसे प्राचीन सभ्यताओं में से एक है। सिंधु घाटी की सभ्यता, मौर्य साम्राज्य, गुप्त वंश, मुगल काल और ब्रिटिश शासन — इन सबने भारत को आकार दिया है। "विविधता में एकता भारत की पहचान है।" महात्मा गांधी ने कहा था: "पहले वे तुम्हें नजरअंदाज करेंगे, फिर तुम पर हंसेंगे, फिर तुमसे लड़ेंगे, और फिर तुम जीत जाओगे।" आजादी की लड़ाई में लाखों लोगों ने अपने प्राण न्योछावर किए। भगत सिंह, सुभाषचंद्र बोस, और रानी लक्ष्मीबाई — ये नाम आज भी प्रेरणा देते हैं। भारत की विविधता इसकी सबसे बड़ी ताकत है; यहां अनेक भाषाएं, धर्म, और परंपराएं एक साथ जीवित हैं।',
      'शिक्षा वह दीपक है, जो अज्ञान के अंधेरे को मिटाता है। एक शिक्षित व्यक्ति न केवल अपने लिए, बल्कि अपने समाज और देश के लिए भी उपयोगी होता है। जब एक बच्चा पहली बार स्कूल जाता है, तो वह एक नई दुनिया में प्रवेश करता है। डॉ. ए.पी.जे. अब्दुल कलाम ने कहा था: "सपने वो नहीं जो नींद में आएं; सपने वो हैं जो आपको नींद न आने दें।" अच्छे शिक्षक छात्रों के जीवन में बड़ा बदलाव लाते हैं। पुस्तकें मानव जाति का सबसे बड़ा खजाना हैं — इनमें सदियों का ज्ञान और अनुभव संचित है। आज के युग में डिजिटल शिक्षा ने ज्ञान को और भी सुलभ बना दिया है; दूर दराज के गांवों में बैठे बच्चे भी अच्छी शिक्षा पा सकते हैं। क्या यह किसी चमत्कार से कम है?',
      'खेल मनुष्य के जीवन का एक महत्वपूर्ण हिस्सा है। क्रिकेट, भारत का सबसे लोकप्रिय खेल, करोड़ों लोगों को एक सूत्र में बांधता है। जब भारतीय टीम मैदान पर उतरती है, तो पूरा देश एक हो जाता है! सचिन तेंदुलकर के बारे में कहा जाता है: "क्रिकेट भारत में एक धर्म है, और सचिन उसके भगवान।" फुटबॉल, हॉकी, बैडमिंटन, कुश्ती, और कबड्डी जैसे खेल भी बहुत लोकप्रिय हैं। खेलों से न केवल शरीर स्वस्थ रहता है, बल्कि मन भी मजबूत होता है। खिलाड़ी टीम भावना, अनुशासन, और हार-जीत को स्वीकार करने का हुनर सीखते हैं; ये गुण जीवन के हर क्षेत्र में काम आते हैं। ग्रामीण क्षेत्रों में भी प्रतिभाएं हैं — उन्हें बस सही मार्गदर्शन और अवसर की जरूरत है।',
      'भारतीय खाना अपनी विविधता और स्वाद के लिए पूरी दुनिया में मशहूर है। उत्तर से दक्षिण, पूर्व से पश्चिम — हर क्षेत्र की अपनी खास व्यंजन परंपरा है। पंजाब की दाल मखनी, दक्षिण भारत के इडली-डोसा, महाराष्ट्र की पूरन पोली, और गुजरात का ढोकला — ये सब अपने आप में एक पूरी संस्कृति को समेटे हुए हैं। "खाना खाने से पहले हाथ धोओ," माँ कहती थीं। भारतीय मसाले जैसे हल्दी, जीरा, धनिया, इलायची, और दालचीनी न केवल खाने को स्वादिष्ट बनाते हैं, बल्कि सेहत के लिए भी बेहद फायदेमंद होते हैं। माँ के हाथ का खाना सिर्फ पेट ही नहीं भरता; मन को भी तृप्त करता है। त्योहारों पर बनने वाले विशेष पकवान — मिठाइयां, नमकीन, और पकवान — उस उत्सव की यादें और भी गहरी बना देते हैं।',
      'नदियां भारत की सभ्यता की जीवनरेखा हैं। गंगा, यमुना, नर्मदा, कावेरी, और ब्रह्मपुत्र — इन नदियों के किनारे ही भारतीय सभ्यता का विकास हुआ है। गंगा को "माँ गंगे" कहा जाता है; वाराणसी, हरिद्वार, और प्रयागराज जैसे शहर इसके किनारे बसे हैं। लेकिन आज ये नदियां प्रदूषण के खतरे से जूझ रही हैं। "नदियों को बचाओ, जीवन बचाओ" — यह नारा आज कितना जरूरी है! कारखानों का कचरा और शहरों का गंदा पानी इन्हें दूषित कर रहा है। इन्हें बचाना हमारी जिम्मेदारी है; हर व्यक्ति को यह समझना होगा कि नदियों की स्वच्छता से ही हमारा भविष्य सुरक्षित है।',
      'भारत का ग्रामीण जीवन एक अलग ही दुनिया है, जहां जीवन की गति शांत और सरल है। सुबह होते ही खेतों में काम शुरू होता है; किसान अपनी भैंस-गाय लेकर खेत जाते हैं। गांव की चौपाल पर बुजुर्ग बैठकर बातें करते हैं, और बच्चे खेल मैदान में दौड़ते-भागते हैं। शाम को मंदिर में आरती होती है, और लोग एक साथ मिलकर प्रार्थना करते हैं। त्योहारों पर पूरा गांव एक परिवार की तरह जुड़ जाता है — होली, दीवाली, ईद, और क्रिसमस सभी मिलजुल कर मनाए जाते हैं। "गांव की माटी में जो प्यार है, वह शहरों में नहीं मिलता।" हालांकि आज गांव भी बदल रहे हैं; सड़कें बन रही हैं, बिजली पहुंच रही है। लेकिन गांव की वह सादगी और अपनापन अभी भी बनी हुई है।',
      'पर्यावरण की रक्षा आज के समय की सबसे बड़ी जरूरत है। जलवायु परिवर्तन पूरी दुनिया के सामने एक बड़ी चुनौती बन गया है। बढ़ता तापमान, पिघलते ग्लेशियर, बेमौसम बारिश, बाढ़, सूखा — ये सब इसके संकेत हैं। पेड़ों की अंधाधुंध कटाई, कारखानों से निकलने वाला धुआं, और वाहनों का प्रदूषण वायु को दूषित कर रहा है। "धरती माँ है; इसे दूषित मत करो।" प्लास्टिक का अत्यधिक उपयोग समुद्रों और नदियों को प्रदूषित कर रहा है। पेड़ लगाना, सौर ऊर्जा का उपयोग करना, प्लास्टिक से बचना, और पानी बचाना — ये छोटे-छोटे कदम मिलकर बड़ा बदलाव ला सकते हैं। भविष्य की पीढ़ियों के लिए एक स्वस्थ धरती छोड़ना हमारी जिम्मेदारी है; इसे आज से ही निभाना शुरू करना होगा।',
      'संगीत मनुष्य की आत्मा की भाषा है। भारतीय शास्त्रीय संगीत की परंपरा हजारों वर्षों पुरानी है। रागों में सात सुर होते हैं — सा, रे, ग, म, प, ध, नि — और इन्हीं सुरों से लाखों राग-रागिनियां बनती हैं। "संगीत वह भाषा है जो सीधे दिल से बात करती है।" लता मंगेशकर, मोहम्मद रफी, किशोर कुमार, और आशा भोसले ने अपनी आवाज से करोड़ों दिलों को छुआ है। लोक संगीत भी उतना ही महत्वपूर्ण है; राजस्थानी मांड, पंजाबी भांगड़ा, बंगाली बाउल, और तमिल लोकगीत अपने-अपने क्षेत्र की संस्कृति की झलक देते हैं। आज की युवा पीढ़ी पश्चिमी संगीत के साथ-साथ भारतीय शास्त्रीय संगीत को भी अपना रही है — और इस मिश्रण से नई, अद्भुत संगीत शैलियां जन्म ले रही हैं।',
    ],
    [
      'आज के डिजिटल युग में तकनीक हमारे जीवन का अभिन्न हिस्सा बन गई है। एक स्मार्टफोन की कीमत ₹10,000 से लेकर ₹1,50,000 तक हो सकती है — और हर कोई पूछता है: "क्या यह इसकी कीमत के लायक है?" सोशल मीडिया पर @BJP4India, @INCIndia जैसे अकाउंट करोड़ों फॉलोअर रखते हैं। #DigitalIndia और #MakeInIndia जैसे हैशटैग ट्रेंड करते रहते हैं। ई-कॉमर्स वेबसाइट्स पर 50% + 10% की छूट देखकर लोग बिना सोचे खरीदारी कर लेते हैं। "डेटा = नया तेल है," टेक विशेषज्ञ कहते हैं। UPI से लेनदेन में 300% की वृद्धि हुई है; ₹100 का भुगतान भी अब QR code से हो जाता है। साइबर सुरक्षा के लिए 8+ अक्षरों का पासवर्ड (जैसे: Bharat@2024!) जरूरी है। क्या आप जानते हैं कि भारत में हर महीने 5 करोड़+ नए इंटरनेट उपयोगकर्ता जुड़ते हैं?',
      'भारतीय शेयर बाजार में निवेश करना अब पहले से आसान हो गया है। BSE और NSE पर ₹500 से भी निवेश शुरू किया जा सकता है। SIP (Systematic Investment Plan) के जरिए मात्र ₹100/माह से म्यूचुअल फंड में निवेश हो सकता है। "Mutual Fund Sahi Hai" — यह नारा आज हर कोई जानता है! Nifty 50 का 52-सप्ताह का उच्च स्तर 26,277 था, जो 15% की वृद्धि दर्शाता है। लेकिन याद रहे: "Investment is subject to market risks (बाजार जोखिम के अधीन)।" Gold ETF, Index Fund, और ELSS (Tax-saving Fund) — ये तीनों विकल्प लोकप्रिय हैं। क्रेडिट कार्ड पर 36-42% वार्षिक ब्याज (APR) लगता है — इसलिए समय पर भुगतान जरूरी है। PPF पर 7.1% और FD पर 6.5-7.5% ब्याज मिलता है। वित्तीय स्वतंत्रता के लिए 50:30:20 का नियम (50% जरूरत, 30% इच्छाएं, 20% बचत) अपनाएं।',
      'स्वास्थ्य ही सबसे बड़ा धन है — यह बात आज पहले से ज्यादा सच है। WHO के अनुसार एक वयस्क को प्रतिदिन कम से कम 30 मिनट व्यायाम करना चाहिए। भारत में डायबिटीज के मरीजों की संख्या 7.7 करोड़+ है — दुनिया में दूसरे नंबर पर! "स्वस्थ शरीर में ही स्वस्थ मन निवास करता है।" Blood pressure की सामान्य range 120/80 mmHg होती है। 8 घंटे की नींद (± 30 मिनट) अनिवार्य है। दिन में 2-3 लीटर पानी पिएं; चाय/कॉफी ≤ 2 कप। Vitamin D की कमी भारत में 70-80% लोगों में पाई जाती है — धूप में बैठना (15-20 मिनट/दिन) इसका सबसे अच्छा उपाय है। Ayurveda + Modern Medicine का संयोजन (Integrative Health) आज ज्यादा लोकप्रिय हो रहा है। याद रखें: Doctor से नियमित check-up (हर 6 महीने) करवाएं — prevention > cure!',
      'भारतीय शिक्षा प्रणाली में बड़े बदलाव आ रहे हैं। NEP 2020 (National Education Policy) के तहत 10+2 की जगह 5+3+3+4 का ढांचा लागू हो रहा है। IIT, IIM, और AIIMS जैसे संस्थान विश्व स्तर पर पहचाने जाते हैं। JEE Advanced में हर साल 1.5 लाख+ छात्र बैठते हैं, लेकिन सीटें मात्र ~16,000 हैं — competition ratio लगभग 1:9 है! "पढ़ोगे-लिखोगे बनोगे नवाब, खेलोगे-कूदोगे होगे खराब" — यह पुरानी सोच अब बदल रही है। CBSE, ICSE, और State Board — तीनों की अपनी खूबियां हैं। Online education platforms जैसे BYJU\'S, Unacademy, और Vedantu ने ₹50,000 करोड़+ का बाजार बनाया है। Coding (Python, Java, C++) आज की जरूरत है — 10वीं के बाद ही सीखना शुरू करें। Scholarship & loan (₹4 लाख तक बिना गारंटी) उपलब्ध हैं; PM-Vidyalakshmi portal पर check करें।',
      'भारत में कृषि अभी भी 58% आबादी की आजीविका का साधन है। MSP (Minimum Support Price) 2024-25 में गेहूं के लिए ₹2,275/क्विंटल तय किया गया है। "किसान की खुशहाली = देश की खुशहाली।" PM-KISAN योजना के तहत ₹6,000/वर्ष (3 किस्तों में) सीधे किसानों के खाते में जाते हैं। Drip irrigation से 40-70% पानी बचता है — और उत्पादन 20-50% बढ़ता है! Organic farming की मांग दुनियाभर में बढ़ रही है; इससे 20-30% ज्यादा कीमत मिलती है। KCC (Kisan Credit Card) पर 4% ब्याज पर ₹3 लाख तक का loan मिलता है। Soil health card से किसान जान सकते हैं कि उनकी जमीन को क्या चाहिए (N, P, K balance)। FPO (Farmer Producer Organizations) के जरिए छोटे किसान मिलकर बड़ा बाजार पा सकते हैं। Technology (drone spraying, AI-based crop monitoring) खेती को #SmartFarming बना रही है।',
      'स्टार्टअप इंडिया की कहानी रोमांचक है। 2016 में शुरू हुई #StartupIndia योजना के बाद से भारत में 1 लाख+ registered startups हैं। यूनिकॉर्न (₹7,500 करोड़+ valuation) की संख्या 100+ हो गई है। "Fail fast, learn faster" — Silicon Valley का यह मंत्र अब Bangalore, Hyderabad, और Pune में भी गूंजता है। Seed funding ₹50 लाख से शुरू होती है; Series A में ₹5-50 करोड़, और Series B में ₹50 करोड़+ मिलते हैं। Fintech (Razorpay, PhonePe), EdTech (BYJU\'S), HealthTech (Practo), और AgriTech (DeHaat) — हर sector में innovation हो रहा है। GST registration, DPIIT recognition, और trademark (@brand) — ये तीन कदम पहले उठाएं। Pitch deck में problem → solution → market size (TAM: ₹10,000 करोड़+) → revenue model → team — यह क्रम जरूरी है। "Ideas are cheap; execution is everything!" याद रखें।',
      'भारतीय सिनेमा, जिसे प्यार से Bollywood कहते हैं, दुनिया का सबसे बड़ा फिल्म उद्योग है। हर साल 1,500+ फिल्में बनती हैं — Hollywood से भी ज्यादा! एक बड़े बजट की फिल्म ₹100-500 करोड़ में बनती है और box office पर ₹1,000 करोड़+ कमाती है। "Cinema is the mirror of society," — यह बात 100% सच है। OTT platforms (Netflix, Amazon Prime, Disney+ Hotstar) ने streaming का तरीका बदल दिया है; subscription ₹149-₹1,499/माह में उपलब्ध है। #BlockbusterHit, #RRR, #Pathaan जैसे hashtags trend करते हैं। Music streaming पर songs billions of times सुने जाते हैं — Spotify, Gaana, और JioSaavn पर। Regional cinema (Tamil, Telugu, Malayalam, Kannada) अब national और international level पर छाई हुई है। Award season में Filmfare, IIFA, और National Film Awards (₹3 लाख + trophy) प्रमुख हैं।',
      'भारत की यात्रा (Tourism) एक अद्भुत अनुभव है। UNESCO की World Heritage Sites की सूची में भारत की 42 sites हैं — Taj Mahal, Qutub Minar, Hampi, और Kaziranga इनमें शामिल हैं। Taj Mahal देखने के लिए Indian tourists को ₹50 और foreign tourists को ₹1,100 की entry fee देनी होती है। "अतिथि देवो भव" — यह भारतीय परंपरा का मूल है। Spiritual tourism (Varanasi, Tirupati, Shirdi, Amritsar) में हर साल करोड़ों श्रद्धालु आते हैं। Adventure tourism: Leh-Ladakh trip (₹25,000-₹50,000), Rishikesh Rafting (₹600-₹1,500), और Andaman Diving (₹2,000-₹5,000) लोकप्रिय हैं। Budget travel: ₹500/रात में hostel, ₹50-₹200 में local transport, और ₹100-₹300 में स्वादिष्ट खाना मिल जाता है। Travel insurance (₹500-₹2,000) जरूर लें! Passport + Visa + travel card (@international) — विदेश यात्रा के लिए ये तीन जरूरी हैं।',
      'भारतीय स्वास्थ्य सेवा क्षेत्र तेजी से बढ़ रहा है। AIIMS, PGI, और CMC Vellore जैसे सरकारी अस्पतालों में treatment लगभग मुफ्त है। Private hospitals में OPD fee ₹200-₹2,000 और surgery ₹50,000-₹5 लाख+ हो सकती है। "Prevention is better than cure (रोकथाम इलाज से बेहतर)।" Ayushman Bharat योजना से ₹5 लाख तक का health cover free मिलता है — 10 करोड़+ परिवार इससे लाभान्वित हो रहे हैं। Generic medicines (Jan Aushadhi Kendra से) branded medicines से 50-90% सस्ती हैं! Telemedicine platform (eSanjeevani) पर अब तक 10 करोड़+ consultations हो चुके हैं — completely free! Blood donation: हर 3 महीने में एक बार donate कर सकते हैं; एक donation 3 lives बचाता है। Mental health पर ध्यान दें — NIMHANS helpline: 080-46110007. Yoga (WHO recognized) + Pranayama रोज 20-30 मिनट करें — ₹0 cost, benefits = priceless!',
      'भारत में renewable energy क्रांति आ रही है। सरकार का लक्ष्य 2030 तक 500 GW renewable energy है — यानी current capacity का 3× से भी ज्यादा! Solar panels की कीमत पिछले 10 साल में 90% घट गई है; ₹30,000-₹50,000 में 1kW rooftop solar system लग जाता है। "The sun is the most reliable power plant (सूर्य सबसे विश्वसनीय बिजलीघर है)।" Wind energy में India दुनिया में चौथे स्थान पर है। PM Surya Ghar scheme से ₹78,000 तक subsidy मिलती है। EV (Electric Vehicles) adoption बढ़ रही है — Ola Electric, Tata Nexon EV, और Ather scooter market lead कर रहे हैं। Charging infrastructure: ₹5-₹8 per kWh (petrol के ₹100/liter vs ₹1.5/km EV cost)। Green Hydrogen production में India बड़ा खिलाड़ी बनने की दिशा में है; National Green Hydrogen Mission में ₹19,744 करोड़ का investment हो रहा है। #ClimateAction #GreenIndia — ये हैशटैग नहीं, जिम्मेदारियां हैं!',
    ],
  ],
];
document.addEventListener("click", function () {
  input.focus();
});
input.addEventListener("input", (e) => {
  const value = e.target.value;
  const span = document.createElement("span");
  span.innerText = value;
  textContainer.appendChild(span);
});
speedDial = document.getElementsByClassName("speed-dial")[0];
let time = Number(speedDial.innerText.slice(0, -1));
localStorage.setItem("total-time", time);
let wrong = 0,
  index = 0,
  total = 0,
  arrIndex = Math.floor(10 * Math.random()),
  str = charString[lang][difficulty][arrIndex];
function write() {
  (textContainer.classList.add("fade-out"),
    setTimeout(() => {
      ((textContainer.innerHTML = ""),
        (arrIndex = Math.floor(10 * Math.random())),
        (str = charString[lang][difficulty][arrIndex]),
        (total = str.length));
      const e = document.createElement("span");
      ((e.innerText = str[0]),
        e.classList.add(yellow),
        textContainer.appendChild(e));
      for (let e = 1; e < str.length; e++) {
        let t = document.createElement("span");
        ((t.textContent = str[e]),
          t.classList.add(grey),
          textContainer.appendChild(t));
      }
      (textContainer.classList.remove("fade-out"),
        textContainer.classList.add("fade-in"));
    }, 200));
}
write();
const spans = textContainer.children;
let last = !0,
  timerStarted = !1;
document.addEventListener("keydown", function (e) {
  if (last) {
    if (1 === e.key.length) {
      if ((totalKeys++, e.preventDefault(), !timerStarted)) {
        ((timerStarted = !0), (start = !0));
        let e = setInterval(function () {
          if ((time--, (speedDial.innerText = `${time}s`), 0 === time)) {
            (localStorage.setItem("time", time),
              localStorage.setItem("total", total),
              localStorage.setItem("wrong", wrong),
              localStorage.setItem("index", index),
              localStorage.setItem("totalKeys", totalKeys),
              localStorage.setItem("difficulty", difficulty),
              localStorage.setItem("lang", lang));
            let t = 0;
            for (let e = 0; e < index; e++)
              spans[e].classList.contains("red-text") && t++;
            (localStorage.setItem("redCount", t),
              (last = !1),
              clearInterval(e),
              (window.location.href = "results.html"));
          }
        }, 1e3);
      }
      if (
        (e.key === str[index]
          ? spans[index].classList.replace(spans[index].classList[0], green)
          : (spans[index].classList.replace(spans[index].classList[0], red),
            wrong++),
        index++,
        index >= str.length)
      ) {
        (localStorage.setItem("time", time),
          localStorage.setItem("total", total),
          localStorage.setItem("wrong", wrong),
          localStorage.setItem("index", index),
          localStorage.setItem("totalKeys", totalKeys),
          localStorage.setItem("difficulty", difficulty),
          localStorage.setItem("lang", lang));
        let e = 0;
        for (let t = 0; t < index; t++)
          spans[t].classList.contains("red-text") && e++;
        (localStorage.setItem("redCount", e),
          (last = !1),
          (window.location.href = "results.html"));
      }
      index < str.length &&
        " " !== str[index] &&
        spans[index].scrollIntoView({
          behavior: "auto",
          block: "center",
          inline: "nearest",
        });
    } else
      "Backspace" === e.key
        ? (e.preventDefault(),
          spans[index].classList.replace(spans[index].classList[0], grey),
          0 !== index && index--,
          index < str.length &&
            " " !== str[index] &&
            spans[index].scrollIntoView({
              behavior: "auto",
              block: "center",
              inline: "nearest",
            }))
        : e.preventDefault();
    index < str.length &&
      spans[index].classList.replace(spans[index].classList[0], yellow);
  }
});
const options = document.getElementsByClassName("option");
let original;
for (let e = 0; e < options.length; e++) {
  let t = options[e];
  t.addEventListener("click", function () {
    if (!timerStarted) {
      let e = t.innerText;
      switch (t.parentElement.parentElement.parentElement.id) {
        case "difficulty":
          switch (((original = difficulty), e)) {
            case "Easy":
              difficulty = 0;
              break;
            case "Medium":
              difficulty = 1;
              break;
            case "Hard":
              difficulty = 2;
          }
          original != difficulty && write();
          break;
        case "time":
          ((time = Number(e.slice(0, -1))),
            localStorage.setItem("total-time", time),
            (speedDial.innerText = `${time}s`));
          break;
        case "language":
          switch (((original = lang), (difficulty = 0), e)) {
            case "English":
              lang = 0;
              break;
            case "हिन्दी":
              lang = 1;
          }
          original != lang && write();
      }
    }
  });
}
